### ISSUE TITLE
This version of webpack plugin is not usable with newer travelm-agency

### ISSUE THREAD

**Issue by kraklin** [anmolitor/travelm-agency-webpack-plugin#169]
I am getting this error when trying to use travelm-agency-webpack-plugin with travelm-agency v 3.5.0.

```
[webpack-cli] TypeError: T.sendTranslations is not a function
      at TravelmAgencyPlugin.<anonymous> (/runner/_work/elm/elm/node_modules/travelm-agency-webpack-plugin/plugin.js:91:21)
      at Generator.next (<anonymous>)
      at /runner/_work/elm/elm/node_modules/travelm-agency-webpack-plugin/plugin.js:31:71
      at new Promise (<anonymous>)
      at __awaiter (/runner/_work/elm/elm/node_modules/travelm-agency-webpack-plugin/plugin.js:27:12)
      at TravelmAgencyPlugin.runTravelmAgency (/runner/_work/elm/elm/node_modules/travelm-agency-webpack-plugin/plugin.js:90:16)
      at TravelmAgencyPlugin.<anonymous> (/runner/_work/elm/elm/node_modules/travelm-agency-webpack-plugin/plugin.js:64:25)
      at Generator.next (<anonymous>)
      at fulfilled (/runner/_work/elm/elm/node_modules/travelm-agency-webpack-plugin/plugin.js:28:58)
```

I have create a PR for the fix as well. #168

**Comment by anmolitor** [comment]
Thank you for your contribution! I merged your PR and released a new version (2.3.0).
